# Publish new GitHub release on PyPI.
name: Publish release

on: [workflow_dispatch]

jobs:

  build:
      name: Build wheel
      runs-on:  ubuntu-latest
      steps:
        - name: Check out code.
          uses: actions/checkout@v4

        - name: Install Python.
          uses: actions/setup-python@v5
          with:
              python-version-file: "pyproject.toml"

        - name: Install UV.
          uses: astral-sh/setup-uv@v5
          with:
              enable-cache: true
              cache-dependency-glob: "uv.lock"

        - name: Build wheel.
          run:  uv build --wheel

        - name: Store wheel.
          uses: actions/upload-artifact@v4
          with:
             name: python-wheel
             path: dist/


  publish:
      name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/')         # Commit must be tagged.
      needs:
        - build
      runs-on: ubuntu-latest
      environment:
          name: pypi
          url:  https://pypi.org/p/SlurmSession
      permissions:
          id-token: write
      steps:
        - name: Download wheel.
          uses: actions/download-artifact@v4
          with:
            name: python-wheel
            path: dist/
        - name: Publish to PyPI.
          uses: pypa/gh-action-pypi-publish@release/v1
