# Report code coverage to Codecov.
name: Report coverage

on: [push, workflow_dispatch]

jobs:

  coverage:
      name: Run tests and collect coverage.
      runs-on: ubuntu-latest
      steps:
        - name: Check out code.
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Install Python.
          uses: actions/setup-python@v5
          with:
              python-version-file: "pyproject.toml"

        - name: Install UV.
          uses: astral-sh/setup-uv@v5
          with:
              enable-cache: true
              cache-dependency-glob: "uv.lock"

        - name: Install package.
          run:  uv sync

        - name: Measure code coverage.
          run:  uv run pytest --cov --cov-report xml

        - name: Upload coverage report.
          uses: codecov/codecov-action@v3
          with:
              token: ${{ secrets.CODECOV_TOKEN }}
              fail_ci_if_error: true
